[logger]
level = "INFO"
format = "text"

[app]
server = "http"
host = "localhost"
port = "8080"
storage = "memory"

[database]
host = "localhost"
port = "5432"
dbname = "hw"
user = "dbuser"
pass = "dbpass"
